---
title: "project"
author: "Anker,Alice,Utsav,James"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
devtools::install_github("ropenscilabs/gendercodeR")
#import libraries
library(tidyverse)
library(janitor)
library(skimr)
library(visdat)
library(gridExtra)
library(gt)
library(kableExtra)
library(GGally)
library(qtlcharts)
library(ggfortify) 
library(sjPlot)
options(knitr.table.format = "html")
```


# Exploratory Data Analysis(EDA)
```{r results ='hide'}
data = read.table("bodyfat.txt",header=TRUE) #read the data

glimpse(data)# Quick glimpse of the data
```
There are 250 observations and 16 variables in this data set. Each row represents an individual response and each column represents the features

```{r results='hide'}
skimr::skim(data)
```
```{r}
#interactive correlation matrix
qtlcharts::iplotCorr(data)
```
```{r}
#extract the data which is storngly correlated to percentage body fat
corr = data %>%
  select(pct_bf,density,weight,chest,abdomen) #select corr > 0.7 or < -0.7
```


```{r}
#correlation matrix
GGally::ggpairs(corr) + theme_bw(base_size = 15)
```

##Fit a simple linear mode

```{r}
lm1 = lm(pct_bf ~ density, data = data) 
summary(lm1)
sjPlot::tab_model(lm1, show.ci = FALSE)
```

```{r}
par(cex = 2) 
plot(pct_bf~density, data = data) 
abline(lm1, lwd = 3, col = "red")
```
```{r}
fitted = 477.2 + (-433.9) * data$density
resid = data$pct_bf - fitted
```


## Chekcing assumptions

###Check linearity
```{r}
#percentage body fat vs density
p1 = ggplot(data, 
              aes(x = density , y = pct_bf)) + 
     geom_point(size = 1) + 
     theme_classic(base_size = 12) + 
     labs(x = "density",
          y = "Percentage body fat") +
     geom_smooth(method = "lm", se = FALSE) 

p2 = ggplot(data, 
            aes(x = density, y = resid)) + 
     geom_point(size = 1) + theme_classic(base_size = 12) + 
     labs(x = "Density", y = "Residual") + 
     geom_hline(yintercept = 0) 

grid.arrange(p1, p2 ,nrow =1, ncol = 2)
```
### Check independenc



### Check homoskedasiticy

```{r}
p2
```
### Check normality

```{r}
autoplot(lm1, which = 1:2)
```


# Modelling

#full linear regression model
```{r}
lm3 = lm(pct_bf ~ density + age + weight + height + neck + chest + abdomen + waist + hip + thigh + knee + ankle + bicep + forearm + wrist, data) 
summary(lm3)
sjPlot::tab_model(lm3, show.ci = FALSE)
```


## 10 fold cross validaiton
```{r}
set.seed(2020)
nrow(data)
```

```{r}
fold_id = c(1, rep(1:10, each = 25))

```

